<?php
include($level.head_path."head.php");
include($level.content_path."Header.php");
include($level.content_path."Banner.php");
include($level.content_path."Modall.php");
//index
if($p_index==true){
//include($level.content_path."Banner2.php");
//include($level.content_path."Bottom.php");
include($level.content_path."Grids.php");
include($level.content_path."Grids2.php");
include($level.content_path."Grids3.php");
}
//Mens
if($p_mens==true)
{
include($level.clothes_path."Buttom_men.php");
include($level.clothes_path."Banner.php");
include($level.clothes_path."Clothers_mens.php");
}
//Womens
if($p_womens==true)
{
include($level.clothes_path."Buttom_wm.php");
include($level.clothes_path."Banner.php");
include($level.clothes_path."Clothes_women.php");
}

//About
if($p_about==true)
{	
include($level.about_path."Banner_Bottom.php");
include($level.about_path."Info.php");
include($level.about_path."Member.php");
include($level.content_path."Bottom.php");
}
//Contact
if($p_contact==true)
{
include($level.contact_path."Bottom_ct.php");
include($level.contact_path."Contact.php");
}
//
include($level.content_path."Coupons.php");
include($level.footer_path."Footer.php");
?>